name: meta_types_firebase
description: models

version: 0.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta_types:
    path: /home/david/workspace/dart_meta_types/meta_types
  built_collection: ^4.0.0

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.8.0
  meta_types_generator: #^0.1.0
    path: /home/david/workspace/dart_meta_types/meta_types_generator

