targets:
  $default:
    builders:
      meta_types_json_generator|meta_types_json:
        enabled: true

builders:
  meta_types_json:
    target: ":meta_types_json_generator"
    import: "package:meta_types_json_generator/builder.dart"
    builder_factories: ["metaTypesjson"]
    build_extensions: {".dart": [".meta_types_json.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]