name: meta_types_redux
version: 0.1.0
description:
  meta_types_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types_redux

dependencies:
  meta: ^1.0.0
  meta_types: ^0.1.0
  redux: ^3.0.0

dev_dependencies:
  build_runner: ^0.9.0
  meta_types_generator: ^0.1.0
  meta_types_redux_generator: ^0.1.0

environment:
  sdk: '>=2-0-0-dev <3.0.0'
