name: meta_types
version: 0.1.0
description:
  metatypes
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types

dependencies:
  built_value: ^7.0.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0

environment:
  sdk: '>=2.7.0 <3.0.0'
