name: meta_types
version: 0.1.0
description:
  metatypes
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types

dependencies:
  built_value: ^6.0.0
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  meta_types_generator: #^0.1.0
    path: /home/david/workspace/dart_meta_types/meta_types_generator

environment:
  sdk: '>=2.2.2 <3.0.0'
