name: meta_types_json
version: 0.0.1
description:
  meta_types_json
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types_json

dependencies:
  meta: ^1.0.0
  meta_types: ^0.1.0

dev_dependencies:
  build_runner: ^0.9.0
  meta_types_generator: ^0.1.0
  meta_types_json_generator: ^0.0.1

environment:
  sdk: '>=2-0-0-dev <3.0.0'
