name: meta_types_firebase_redux
version: 0.1.0
description:
  meta_types_firebase_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types_firebase_redux

dependencies:
  meta: ^1.0.0
  meta_types:
    path: ../meta_types
  firebase: ^5.0.0
  flutter_hooks: ^0.4.0

dev_dependencies:
  build_runner: ^1.0.0
  # meta_types_generator: ^0.1.0
  meta_types_generator:
    path: ../meta_types_generator

environment:
  sdk: '>=2-0-0-dev <3.0.0'
