name: meta_types_generator
version: 0.1.0
description:
  meta_types_generator
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/dart_meta_types/meta_types_generator

dependencies:
  analyzer: ^0.32.0
  build: ^0.12.0
  source_gen: ^0.9.0
  meta_types: ^0.1.0
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  test: ^1.0.0

environment:
  sdk: '>=2-0-0-dev <3.0.0'
